config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'
	resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true, length: { maximum:50 }
	validates :age, presence: true, numericality: { only_integer: true }
	validates :softness, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 11 } 
	validates :cuteness, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.xml { render xml: @kittens}
			format.json { render json: @kittens}
		end
	end
	def new
		@kitten = Kitten.new
	end
	def show
		@kitten = Kitten.find(params[:id])
	end
	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "New Kitten Created!!!"
			redirect_to root_url
		else
			render 'new'
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten Updated!"
			redirect_to @kitten
		else
			render 'edit'
		end
	end

	def destroy
		Kitten.find(params[:id]).destroy
		flash[:success] = "Kitten Deleted!"
		redirect_to kittens_url
	end

	private

	def kitten_params
		params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>	

	<%= f.label :age %>
	<%= f.number_field :age, class: 'form-control' %>	

	<%= f.label :cuteness%>
	<%= f.number_field :cuteness, class: 'form-control' %>	

	<%= f.label :softness %>
	<%= f.number_field :softness, class: 'form-control' %>
	<br>
	<%= f.submit "Meow", class: "btn btn-info"%>
<% end %>

app/views/kittens/edit.html.erb
<div class="container">
	<div class="row">
		<%=render 'form' %>
	</div>
</div>

app/views/kittens/index.html.erb
	<div class="row">
			<% @kittens.each do|kitten| %>
				<ol class="clearfix">
					<h3 class="list-group-item"><%=link_to kitten.name, kitten%></h3>
					<li class="list-group-item">Age: <%=kitten.age%></li>
					<li class="list-group-item">Cuteness: <%=kitten.cuteness%></li>
					<li class="list-group-item">Softness: <%=kitten.softness%></li>
<!-- 					<li class="list-group-item">
						<button type="button" class="btn btn-info">
							<%=link_to "delete", @kitten, method: :delete, data: { confirm: "You sure?" }%>
						</button>
					</li> -->
				</ol>
			<% end %> 
	</div>
	<div class="row">
		<%= link_to 'New Kitten', new_kitten_path, class: 'btn btn-info' %> 
	</div>
</div>

app/views/kittens/new.html.erb
<div class="container">
	<div class="row">
		<%=render 'form' %>
	</div>
</div>

app/views/kittens/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<ul class="">
					<h3 class="list-group-item"><%=link_to @kitten.name, @kitten%></h3>
					<li class="list-group-item">How Old? <%= @kitten.age%></li>
					<li class="list-group-item">How Cute?? <%= @kitten.cuteness%></li>
					<li class="list-group-item">How Soft??? <%= @kitten.softness%></li>
			</ul>
		</div>
		<div class="col-md-4">
		</div>
	</div>
	<div class="row">
		<div class="col">
			<button type="button" class="btn btn-info">
				<%=link_to "delete", @kitten, method: :delete, data: { confirm: "You sure?" }%>
			</button>
			
		</div>
	</div>
	
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%=link_to "Home", root_path%></li>
				<li><%=link_to "About", "#"%></li>
				<li><%=link_to "New Kitten", new_kitten_path %></li>
			</ul>
		</nav>
	</div>
</header>

<div class="container">
	<div class="row">
			<div class="jumbotron">
				<h1 class="text-center">Kittens!!!</h1>
			</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <!-- <div class="alert alert-<%= message_type %>"><%= message %></div> -->
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>